# frozen_string_literal: true

require 'parslet'
require_relative 'systemrdl/version'
require_relative 'systemrdl/node/identifier'
require_relative 'systemrdl/node/literal'
require_relative 'systemrdl/node/number_literal'
require_relative 'systemrdl/node/enumerator_literal'
require_relative 'systemrdl/node/struct_literal'
require_relative 'systemrdl/node/array_literal'
require_relative 'systemrdl/node/unary_operation'
require_relative 'systemrdl/node/binary_operation'
require_relative 'systemrdl/node/ternary_operation'
require_relative 'systemrdl/node/concatenation'
require_relative 'systemrdl/node/multiple_concatenation'
require_relative 'systemrdl/parser'
require_relative 'systemrdl/parser/identifiers'
require_relative 'systemrdl/parser/literals'
require_relative 'systemrdl/parser/expressions'
require_relative 'systemrdl/parser/concatenation'
