name: CI

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ['3.0', '2.7', '2.6', '2.5', '2.4']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run RSpec
        run: |
          bundle exec rake coverage
